// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgfjziursiqjrnaxqamy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZmp6aXVyc2lxanJuYXhxYW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDU5NjEsImV4cCI6MjA3MTAyMTk2MX0.zFOk2kxM5IAYPgaLRtjUo4Qba1QpccagifB5MGjXTSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});